version: "3"
services:

  appjava1:
    build: ./App1
    ports:
      - "7766:7777"
    container_name: appjava1
  
  appjava2:
    build: ./App2
    ports:
       - "8866:8888"
    container_name: appjava2

  nginx:
    image: reverse-proxy
    ports:
      - "80:80"
    container_name: project_reverse-proxy
